#
# Copyright Strimzi authors.
# License: Apache License 2.0 (see the file LICENSE or http://apache.org/licenses/LICENSE-2.0.html).
#
kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: strimzi-traffic-generator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: strimzi-traffic-generator
    spec:
      restartPolicy: Always
      containers:
        - name: traffic-generator
          image: quay.io/jhellar/go-stoker:latest
          volumeMounts:
            - name: cluster-ca
              mountPath: /etc/cluster-ca
              readOnly: true
            - name: client-ca
              mountPath: /etc/client-ca
              readOnly: true
            - name: client-ca-cert
              mountPath: /etc/client-ca-cert
              readOnly: true
          env:
            - name: KAFKA_BOOTSTRAP_URL
              value: 'my-cluster-kafka-bootstrap-kafka-cluster.apps.damurphy.f7b1.s1.devshift.org:9094'
            - name: PRODUCER_TRAFFIC_TOPIC
              value: 'traffic-gen-topic'
            - name: PRODUCER_TRAFFIC_SEND_RATE_IN_SEC
              value: '5'
            - name: PRODUCER_CLIENT_ID
              value: 'traffic-gen-client'
            - name: TLS_ENABLED
              value: 'false'
      volumes:
        - name: cluster-ca
          secret:
            secretName: my-cluster-cluster-ca-cert
            defaultMode: 288
        - name: client-ca-cert
          secret:
            secretName: my-cluster-clients-ca-cert
            defaultMode: 288
        - name: client-ca
          secret:
            secretName: my-cluster-clients-ca
            defaultMode: 288
          imagePullPolicy: IfNotPresent
      dnsPolicy: ClusterFirst
  triggers:
    - type: ConfigChange
